# Generated by Django 4.2.2 on 2023-11-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_is_type1_user_profile_is_type2_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_type1_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_type2_user',
        ),
    ]
