# Generated by Django 4.2.2 on 2023-11-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
    ]
