# Generated by Django 4.2.2 on 2023-11-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_chapter_delete_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs'),
        ),
    ]
